import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import Image from "../models/Image.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const UPLOAD_ROOT = path.join(__dirname, "..", "uploads");

// Ensure base upload directory exists
if (!fs.existsSync(UPLOAD_ROOT)) {
  fs.mkdirSync(UPLOAD_ROOT, { recursive: true });
}

// @desc    Upload an image
// @route   POST /api/images/upload
export const uploadImage = async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ message: "No file provided" });

    // req.file path is generated by multer inside the middleware
    const imagePath = `/uploads/${req.user._id}/${req.file.filename}`;

    const newImage = new Image({
      userId: req.user._id,
      filename: req.file.filename,
      filepath: imagePath,
      mimetype: req.file.mimetype,
      size: req.file.size
    });

    const savedImage = await newImage.save();
    res.status(201).json(savedImage);
  } catch (error) {
    console.error("Image Upload Error:", error);
    res.status(500).json({ message: "Error uploading image" });
  }
};

// @desc    Stream an image securely to its owner
// @route   GET /api/images/:id
export const streamImage = async (req, res) => {
  try {
    const image = await Image.findOne({
      _id: req.params.id,
      userId: req.user._id // Absolute Zero-Trust Ownership Check
    });

    if (!image) return res.status(404).json({ message: "Image not found or unauthorized" });

    const absoluteFilePath = path.join(UPLOAD_ROOT, req.user._id.toString(), image.filename);
    
    if (!fs.existsSync(absoluteFilePath)) {
      return res.status(404).json({ message: "File missing from disk" });
    }

    res.sendFile(absoluteFilePath);
  } catch (error) {
    console.error("Image Stream Error:", error);
    res.status(500).json({ message: "Error streaming image" });
  }
};

// @desc    Get all images belonging to the user for the Gallery
// @route   GET /api/images
export const getImages = async (req, res) => {
  try {
    const images = await Image.find({ userId: req.user._id }).sort({ createdAt: -1 });
    res.json(images);
  } catch (error) {
    console.error("Fetch Images Error:", error);
    res.status(500).json({ message: "Error fetching images" });
  }
};
